dist: trusty
sudo: false
matrix:
  include:
    before_install:
      - cd TemperatureSensor
    language: node_js
    node_js:
      - "8.9.4"
    script: true
    deploy:
      provider: script
      script: bash deploy.sh
      on:
        branch: master